version: '3'
services:
  app:
    build: .
    stdin_open: true            # Keeps STDIN open
    tty: true                   # Allocates terminal
    depends_on:
      - database
    container_name: my-app      #Fixed name for container
    restart: "no"

  database:
    build: database/.
    restart: always
    ports:
      - "33060:3306"